    def testRegistration(self) -> None:
        driver = self.driver
        driver.find_element(by=AppiumBy.ID, value="com.example.aplikasi_absen:id/avStart_card_signup").click()
        driver.implicitly_wait(4)
        fullname_textfield = driver.find_element(by=AppiumBy.ID, value="com.example.aplikasi_absen:id/ipt_fullname")
        fullname_textfield.click()
        fullname_textfield.send_keys("Aarti Gandhi")
        email_textfield = driver.find_element(by=AppiumBy.ID, value="com.example.aplikasi_absen:id/ipt_email")
        email_textfield.click()
        email_textfield.send_keys("aartikshah.1@gmail.com")
        phone_number_field = driver. find_element(by=AppiumBy.ID, value="com.example.aplikasi_absen:id/ipt_phonenumber")
        phone_number_field.click()
        phone_number_field.send_keys("+46764555748")
        address_textfield = driver.find_element(by=AppiumBy.ID, value="com.example.aplikasi_absen:id/ipt_address")
        address_textfield.click()
        address_textfield.send_keys("Solna")
        password_textfield = driver.find_element(by=AppiumBy.ID, value="com.example.aplikasi_absen:id/ipt_password")
        password_textfield.click()
        password_textfield.send_keys("testing1234*")
        reset_password = driver.find_element(by=AppiumBy.ID, value="com.example.aplikasi_absen:id/ipt_confirmpassword")
        reset_password.click()
        reset_password.send_keys("testing1234*")
